apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web-service
    spec:
      containers:
        - name: web-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env }}

