apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-web-gateway
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port }}
      routes:
        - kind: HTTPRoute
          name: {{ .Release.Name }}-web-route
