apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-web-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Release.Name }}-web-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      forwordTo:
        - serviceName: {{ .Release.Name }}-web-service
          port: {{ .Values.service.port }}

